<ENV>:
  base_url: <BASE_URL>
  internal_base_url: <INTERNAL_BASE_URL>
  api_key:
    gpd: <API_KEY_GPD>
    aca: <API_KEY_ACA>
  user_info:
    admin_org_gpd:
      user_id: <ADMIN_ORG_GPD_USER_ID>
    admin_org_aca:
      user_id: <ADMIN_ORG_ACA_USER_ID>
  organization:
    aca:
      fiscal_code: <ORG_FISCAL_CODE_ACA>
      ipa_code: <IPA_CODE_ACA>
      name: <NAME_ACA>
      iban: <IBAN_ACA>
      has_generate_notice_api_key: False | True
    gpd:
      fiscal_code: <ORG_FISCAL_CODE_GPD>
      ipa_code: <IPA_CODE_GPD>
      name: <NAME_GPD>
      iban: <IBAN_GPD>
      has_generate_notice_api_key: False | True
  citizen_info:
    name: <CITIZEN_NAME>
    fiscal_code: <CITIZEN_FISCAL_CODE>
    email: <CITIZEN_EMAIL>
  send_info:
    gpd:
      client_id: <CLIENT_ID_GPD>
      client_secret: <CLIENT_SECRET_GPD>
    aca:
      client_id: <CLIENT_ID_ACA>
      client_secret: <CLIENT_SECRET_ACA>
    citizen:
      fiscal_code: <SEND_CITIZEN_FISCAL_CODE>
  sil_info:
    gpd:
      client_id: <CLIENT_ID_SIL_GPD>
      client_secret: <CLIENT_SECRET_SIL_GPD>
  payment_info:
    broker_fiscal_code: <BROKER_FISCAL_CODE>
    broker_station_id: <BROKER_STATION_ID>
    psp:
      id: <PSP_ID>
      id_broker: <PSP_ID_BROKER>
      id_channel: <PSP_ID_CHANNEL>
      password: <PDP_PASSWORD>